"""add_is_admin_column

Revision ID: b0ca3f07d894
Revises: b2c3d4e5f6a7
Create Date: 2026-06-04 17:31:53.372829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ca3f07d894'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    # Reset users_id_seq sequence to prevent unique constraint violation
    op.execute("SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 1));")

    # Seed default admin user: admin@bankguard.com / adminpassword
    op.execute("""
    INSERT INTO users (name, email, password_hash, is_admin, created_at)
    VALUES ('Admin User', 'admin@bankguard.com', '$2b$12$XdufqOP5X4JMgQWqph3qROrUHEXRcQaq6xfmgzXDPHe.gfqrbxm9q', true, NOW())
    ON CONFLICT (email) DO NOTHING;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Remove seeded admin user
    op.execute("DELETE FROM users WHERE email = 'admin@bankguard.com';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
