from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from database import get_db
from models.transaction import Transaction
from models.account import Account
from schemas.transaction import TransactionCreate

from models.fraud_event import FraudEvent
from dependencies import get_current_user
from models.user import User

router = APIRouter(
    prefix="/transactions",
    tags=["Transactions"]
)


@router.post("/")
async def create_transaction(
    transaction: TransactionCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):

    query = select(Account).where(
        Account.id == transaction.account_id,
        Account.user_id == current_user.id
    )

    result = await db.execute(query)

    account = result.scalar_one_or_none()

    if not account:

        raise HTTPException(
            status_code=403,
            detail="You do not own this account"
        )

    new_transaction = Transaction(
        account_id=transaction.account_id,
        amount=transaction.amount,
        merchant_name=transaction.merchant_name,
        merchant_category=transaction.merchant_category,
        city=transaction.city,
        country=transaction.country,
        ip_address=transaction.ip_address,
        device_id=transaction.device_id
        # risk_score, decision, and fraud_flags will be automatically computed by DB triggers BEFORE INSERT
    )

    db.add(new_transaction)
    await db.commit()

    # Refresh to retrieve the computed fields (risk_score, decision, fraud_flags, and generated ID)
    await db.refresh(new_transaction)

    # Fetch the details generated by the AFTER INSERT trigger on fraud_events
    events_query = select(FraudEvent).where(
        FraudEvent.transaction_id == new_transaction.id
    )
    events_result = await db.execute(events_query)
    events = events_result.scalars().all()
    details = {event.rule_triggered: event.details for event in events}

    return {
        "message": "Transaction processed",
        "transaction_id": new_transaction.id,
        "risk_score": new_transaction.risk_score,
        "decision": new_transaction.decision,
        "triggered_rules": new_transaction.fraud_flags,
        "details": details
    }